### ISSUE TITLE
dashborad can't work

### ISSUE THREAD

**Issue by linuxwind** [rochaporto/dashing-ceph#1] opened 2014-03-13 10:39 UTC
OS: Centos 6.5

when i run the start command get this error:
# dashing start

Thin web server (v1.6.2 codename Doc Brown)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
192.168.10.119 - - [13/Mar/2014 18:35:22] "GET /ceph HTTP/1.1" 200 2002 0.0040
Warning. Error encountered while saving cache c0cce031fa65eaded25bcaab9d5a81b07e8c62e0/application.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 71b977c8e24caaa0500d85b58a47db260f27a509/clock.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 302b7cfed19453b8b8489e1e0f415878a4dfda5e/comments.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 1c4349651adf4f04128bf414c9f59aa9b4bbd18d/graph.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache e996cbe96f85a7ce41dc89d5214f8f5ae61afeed/health.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 4da0370406029e77754f51f8b7c60ac10507043f/iframe.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 26e948a4608a9a16fa89b63a04bb0f1bf8ab7911/image.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache ee32f1adad50345df4a32105ce5bf3fd5d1a0ee1/list.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 3230c8c466f4784923f892f6e96fccb510522cde/meter.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 655e91beae7125d3092c25f0d0a763b68d620f27/mgraph.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 3157b7a144ad587416127c143a3fc82850abd756/number.scssc: can't dump anonymous class #Class:0x00000002ac8850
Warning. Error encountered while saving cache 4ca71de36368509ac57533d7b8f122b44b23e5b8/text.scssc: can't dump anonymous class #Class:0x00000002ac8850

I think it must be a sass bug.
so edit this file:
/opt/rh/ruby193/root/usr/local/share/gems/gems/sass-3.3.2/lib/sass/engine.rb
...
DEFAULT_OPTIONS = {
      :style => :nested,
      :load_paths => ['.'],
      :cache => true,             <===== make it to false
      :cache_location => './.sass-cache',
      :syntax => :sass,
      :filesystem_importer => Sass::Importers::Filesystem
    }.freeze
....

then start thin web server:

I get nothing. 
no ceph cluster status on the web. could you help me fix it?

**Comment by rochaporto** [comment] 2014-03-17 04:23
Hi.

I don't think the issue is related to the caching - i see the same warnings in my local environment, but it still works.

Do you have a working ceph client in the host you're running dashing? Does something like:

```
    ceph health
```

work when you issue the command as the same user running dashing? Check you have the client.admin keyring available (and working), and also permissions for access to that file by the user running dashing.

Ricardo

**Comment by rochaporto** [comment] 2014-03-25 21:04
Hi.

Are you still having this issue? I'll close it otherwise.

Cheers,
  Ricardo

**Closed as completed** 2014-04-01 20:40 UTC
